accessKey
: 
""
align
: 
"center"
attributeStyleMap
: 
StylePropertyMap {size: 0}
attributes
: 
NamedNodeMap {0: align, align: align, length: 1}
autocapitalize
: 
""
autofocus
: 
false
baseURI
: 
"https://asl.ms/()/().htm"
childElementCount
: 
1
childNodes
: 
NodeList(2) [text, form#asl_words]
children
: 
HTMLCollection [form#asl_words, asl_words: form#asl_words]
classList
: 
DOMTokenList [value: '']
className
: 
""
clientHeight
: 
477
clientLeft
: 
0
clientTop
: 
0
clientWidth
: 
719
contentEditable
: 
"inherit"
currentCSSZoom
: 
1
dataset
: 
DOMStringMap {}
dir
: 
""
draggable
: 
false
elementTiming
: 
""
enterKeyHint
: 
""
firstChild
: 
text
firstElementChild
: 
form#asl_words
hidden
: 
false
id
: 
""
inert
: 
false
innerHTML
: 
" \n\t\t<form action=\"#\" method=\"post\" name=\"asl_words\" id=\"asl_words\" onsubmit=\"return check_word()\"> \n<p style=\"margin-top: 0; margin-bottom: 0\"><font face=\"Arial\">&nbsp;</font></p><font face=\"Arial\">\n<img src=\"images/blank.gif\" alt=\"Click on NEW WORD (may take a moment to load)...\" title=\"loading...\" name=\"ASLalphabet\" id=\"ASLalphabet\" border=\"1\" height=\"240\" width=\"240\"> \n<br> \n<input class=\"button\" name=\"refresh\" value=\"new word\" accesskey=\"n\" onclick=\"new_word()\" type=\"button\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\">&nbsp;&nbsp;&nbsp; \n<input class=\"button\" value=\"replay\" name=\"repeat\" type=\"button\" accesskey=\"r\" onclick=\"change_speed2()\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\">&nbsp;&nbsp; \n<hr color=\"#000080\" noshade=\"noshade\" size=\"1\" width=\"290\"> \n<p style=\"margin-top: 0pt; margin-bottom: 0pt;\">Type your answer here:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; <br>  \n<br> \n \n<input name=\"input\" id=\"answerInput\" size=\"25\" maxlength=\"20\" tabindex=\"1\" class=\"input\" type=\"text\" style=\"background-color: #00FFFF; font-size:14pt; font-family:Arial\">&nbsp;&nbsp; \n<input class=\"button\" name=\"check\" value=\"check\" type=\"submit\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\"></p> \n<hr color=\"#800080\" noshade=\"noshade\" size=\"1\" width=\"290\"> \n<p style=\"margin-top: 0; margin-bottom: 0\">  \nMaximum number of letters?&nbsp;&nbsp; \n<input class=\"button\" name=\"letters\" value=\"3\" onclick=\"set_length_lim(3)\" type=\"radio\"> 3&nbsp;&nbsp;\n<input class=\"button\" name=\"letters\" value=\"4\" onclick=\"set_length_lim(4)\" type=\"radio\"> 4&nbsp;&nbsp;\n<input class=\"button\" name=\"letters\" value=\"5\" onclick=\"set_length_lim(5)\" type=\"radio\"> 5&nbsp;&nbsp;\n<input class=\"button\" name=\"letters\" value=\"6\" onclick=\"set_length_lim(6)\" type=\"radio\"> 6&nbsp; \n<input class=\"button\" name=\"letters\" value=\"Any length\" onclick=\"set_length_lim(99)\" type=\"radio\"> \nany </p><p style=\"margin-top: 0; margin-bottom: 0\"> \nSet your speed: &nbsp; \n<input class=\"button\" name=\"speed\" value=\"slow\" accesskey=\"s\" onclick=\"change_speed(0)\" tabindex=\"2\" type=\"radio\"> slow&nbsp;&nbsp; \n<input class=\"button\" name=\"speed\" value=\"medium\" accesskey=\"m\" onclick=\"change_speed(1)\" type=\"radio\" checked=\"\"> medium&nbsp;&nbsp; \n<input class=\"button\" name=\"speed\" value=\"fast\" accesskey=\"f\" onclick=\"change_speed(2)\" type=\"radio\"> fast&nbsp;&nbsp; \n<input class=\"button\" name=\"speed\" value=\"Deaf\" accesskey=\"d\" onclick=\"change_speed(3)\" type=\"radio\"> Deaf</p> \n<p style=\"margin-top: 0; margin-bottom: 0\"> \nFine tune your speed: &nbsp; \n<input class=\"button\" name=\"slower\" value=\"slower\" onclick=\"set_speed(0)\" tabindex=\"2\" type=\"button\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\">&nbsp;&nbsp; \n<input class=\"button\" name=\"faster\" value=\"faster\" onclick=\"set_speed(1)\" type=\"button\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\"></p><p style=\"margin-top: 0; margin-bottom: 0\"> \n</p><p>Your score <b id=\"scoretxt\">2</b> </p></font></form>"
innerText
: 
" \n\n\n      \n\nType your answer here:               \n\n   \n\nMaximum number of letters?    3    4    5    6   any\n\nSet your speed:    slow    medium    fast    Deaf\n\nFine tune your speed:      \n\nYour score 2"
inputMode
: 
""
isConnected
: 
true
isContentEditable
: 
false
lang
: 
""
lastChild
: 
form#asl_words
lastElementChild
: 
form#asl_words
localName
: 
"div"
namespaceURI
: 
"http://www.w3.org/1999/xhtml"
nextElementSibling
: 
font
nextSibling
: 
font
nodeName
: 
"DIV"
nodeType
: 
1
nonce
: 
""
offsetHeight
: 
477
offsetLeft
: 
1
offsetParent
: 
td
offsetTop
: 
1
offsetWidth
: 
719
outerHTML
: 
"<div align=\"center\"> \n\t\t<form action=\"#\" method=\"post\" name=\"asl_words\" id=\"asl_words\" onsubmit=\"return check_word()\"> \n<p style=\"margin-top: 0; margin-bottom: 0\"><font face=\"Arial\">&nbsp;</font></p><font face=\"Arial\">\n<img src=\"images/blank.gif\" alt=\"Click on NEW WORD (may take a moment to load)...\" title=\"loading...\" name=\"ASLalphabet\" id=\"ASLalphabet\" border=\"1\" height=\"240\" width=\"240\"> \n<br> \n<input class=\"button\" name=\"refresh\" value=\"new word\" accesskey=\"n\" onclick=\"new_word()\" type=\"button\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\">&nbsp;&nbsp;&nbsp; \n<input class=\"button\" value=\"replay\" name=\"repeat\" type=\"button\" accesskey=\"r\" onclick=\"change_speed2()\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\">&nbsp;&nbsp; \n<hr color=\"#000080\" noshade=\"noshade\" size=\"1\" width=\"290\"> \n<p style=\"margin-top: 0pt; margin-bottom: 0pt;\">Type your answer here:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; <br>  \n<br> \n \n<input name=\"input\" id=\"answerInput\" size=\"25\" maxlength=\"20\" tabindex=\"1\" class=\"input\" type=\"text\" style=\"background-color: #00FFFF; font-size:14pt; font-family:Arial\">&nbsp;&nbsp; \n<input class=\"button\" name=\"check\" value=\"check\" type=\"submit\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\"></p> \n<hr color=\"#800080\" noshade=\"noshade\" size=\"1\" width=\"290\"> \n<p style=\"margin-top: 0; margin-bottom: 0\">  \nMaximum number of letters?&nbsp;&nbsp; \n<input class=\"button\" name=\"letters\" value=\"3\" onclick=\"set_length_lim(3)\" type=\"radio\"> 3&nbsp;&nbsp;\n<input class=\"button\" name=\"letters\" value=\"4\" onclick=\"set_length_lim(4)\" type=\"radio\"> 4&nbsp;&nbsp;\n<input class=\"button\" name=\"letters\" value=\"5\" onclick=\"set_length_lim(5)\" type=\"radio\"> 5&nbsp;&nbsp;\n<input class=\"button\" name=\"letters\" value=\"6\" onclick=\"set_length_lim(6)\" type=\"radio\"> 6&nbsp; \n<input class=\"button\" name=\"letters\" value=\"Any length\" onclick=\"set_length_lim(99)\" type=\"radio\"> \nany </p><p style=\"margin-top: 0; margin-bottom: 0\"> \nSet your speed: &nbsp; \n<input class=\"button\" name=\"speed\" value=\"slow\" accesskey=\"s\" onclick=\"change_speed(0)\" tabindex=\"2\" type=\"radio\"> slow&nbsp;&nbsp; \n<input class=\"button\" name=\"speed\" value=\"medium\" accesskey=\"m\" onclick=\"change_speed(1)\" type=\"radio\" checked=\"\"> medium&nbsp;&nbsp; \n<input class=\"button\" name=\"speed\" value=\"fast\" accesskey=\"f\" onclick=\"change_speed(2)\" type=\"radio\"> fast&nbsp;&nbsp; \n<input class=\"button\" name=\"speed\" value=\"Deaf\" accesskey=\"d\" onclick=\"change_speed(3)\" type=\"radio\"> Deaf</p> \n<p style=\"margin-top: 0; margin-bottom: 0\"> \nFine tune your speed: &nbsp; \n<input class=\"button\" name=\"slower\" value=\"slower\" onclick=\"set_speed(0)\" tabindex=\"2\" type=\"button\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\">&nbsp;&nbsp; \n<input class=\"button\" name=\"faster\" value=\"faster\" onclick=\"set_speed(1)\" type=\"button\" style=\"color: #00FFFF; font-family: arial; border: 2px solid #000080; background-color: #000000\"></p><p style=\"margin-top: 0; margin-bottom: 0\"> \n</p><p>Your score <b id=\"scoretxt\">2</b> </p></font></form></div>"
outerText
: 
" \n\n\n      \n\nType your answer here:               \n\n   \n\nMaximum number of letters?    3    4    5    6   any\n\nSet your speed:    slow    medium    fast    Deaf\n\nFine tune your speed:      \n\nYour score 2"
ownerDocument
: 
document
parentElement
: 
td
parentNode
: 
td
part
: 
DOMTokenList [value: '']
previousSibling
: 
text
scrollHeight
: 
477
scrollLeft
: 
0
scrollTop
: 
0
scrollWidth
: 
719
slot
: 
""
spellcheck
: 
true
style
: 
CSSStyleDeclaration {accentColor: '', additiveSymbols: '', alignContent: '', alignItems: '', alignSelf: '', …}
tabIndex
: 
-1
tagName
: 
"DIV"
textContent
: 
" \n\t\t \n \n \n \n    \n   \n \nType your answer here:                  \n \n \n   \n \n \n  \nMaximum number of letters?   \n 3  \n 4  \n 5  \n 6  \n \nany  \nSet your speed:   \n slow   \n medium   \n fast   \n Deaf \n \nFine tune your speed:   \n   \n \nYour score 2 "
title
: 
""
translate
: 
true
virtualKeyboardPolicy
: 
""
writingSuggestions
: 
"true"
